from automata_inicio import *
from automata_fin import *
from automata_escribe import *
from PUNTO_COMA import *
from cadenas import *
##from automata_captura import *
##from automata_si import *
##from automata_entonces import *
##from automata_sino import *
##from automata_finsi import *
##from automata_acaso import *
##from automata_casa import *
##from automata_ninguno import *
##from automata_fincaso import *
##from automata_desde import *
##from automata_hasta import *
##from automata_intervalo import *
##from automata_haz import *
##from automata_mientras import *
##from automata_finhaz import *
##from automata_ejecuta import *
##from automata_signo import *
##from automata_signo2 import *
##from automata_signo3 import *
##from automata_signo4 import *
##from automata_signo5 import *
##from COMENTARIOS import *
##from const_numericas import *
##from ESPACIO import *
##from identificadores import *
##from punto import *
##from admiracion import *
##from et import *
##from guion import *
##from mas import *
##from exponencial import *
##from AND import *
##from AUT import *
##from BLO import *
##from CAD import *
##from CRU import *
##from EXT import *
##from WEL import *
##from YOV import *

